-- AlterTable
ALTER TABLE "User" ADD COLUMN     "loseTiming" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "matchHistory" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "mmr" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "ping" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "playStyle" TEXT NOT NULL DEFAULT 'balanced',
ADD COLUMN     "reports" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "winRate" DOUBLE PRECISION NOT NULL DEFAULT 50.0,
ADD COLUMN     "winTiming" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
